export interface FinderDropdown {
  name: string
  items: string[]
}

export const Finder: FinderDropdown[] = [
  {
    name: 'Finder',
    items: [
      'About Finder',
      'Settings...',
      'Empty Trash',
      'Services',
      'Hide Finder',
      'Hide Others',
      'Show All',
    ],
  },
  {
    name: 'File',
    items: [
      'New Finder Window',
      'New Folder',
      'New Folder with Selection',
      'New Smart Folder',
      'New Tab',
      'Open',
      'Open With',
      'Print',
      'Close Window',
      'Get Info',
      'Rename',
      'Compress',
      'Duplicate',
      'Make Alias',
      'Quick Look',
      'Print',
      'Share...',
      'Show Original',
      'Add to sidebar',
      'Move to Trash',
      'Eject',
      'Rename',
      'Tags...',
      'Find',
    ],
  },
  {
    name: 'Edit',
    items: [
      'Undo',
      'Redo',
      'Cut',
      'Copy',
      'Paste',
      'Select All',
      'Show Clipboard',
      'Start Dictation',
      'Emoji & Symbols',
    ],
  },
  {
    name: 'View',
    items: [
      'as Icons',
      'as List',
      'as Columns',
      'Use Stacks',
      'Sort By',
      'as Gallery',
      'Clean Up',
      'Clean Up By',
      'Hide Sidebar',
      'Hide Preview',
      'Hide Toolbar',
      'Show All Tabs',
      'Hite Tab Bar',
      'Hide Path Bar',
      'Hide Status Bar',
      'Customize Toolbar...',
      'Show View Options',
      'Show Path Bar',
      'Enter Full Screen',
    ],
  },
  {
    name: 'Go',
    items: [
      'Back',
      'Forward',
      'Enclosing Folder',
      'Recents',
      'Documents',
      'Desktop',
      'Downloads',
      'Home',
      'Computer',
      'AirDrop',
      'Network',
      'iCloud Drive',
      'Shared',
      'Applications',
      'Utilities',
      'Recents Folders',
      'Go to Folder...',
      'Connect to Server...',
    ],
  },
  {
    name: 'Window',
    items: [
      'Minimize',
      'Zoom',
      'Cycle Through Windows',
      'Bring All to Front',
      'All',
      'None',
      'Minimize All',
      'Arrange in Front',
      'Move Tab to New Window',
      'Merge All Windows',
    ],
  },
  { name: 'Help', items: ['Help Center', 'Show Help Center', 'Search...'] },
]
