import { Item } from "../../../@types/item"

export interface FinderDropdown {
  name: string
  items: Item[]
}

export const Finder: FinderDropdown[] = [
  {
    name: 'Finder',
    items: [
      {
        name: 'About Finder',
        handleButtonFunction: () => console.log('About This Mac'),
        hasSection: true,
      },
      {
        name: 'Settings',
        handleButtonFunction: () => console.log('About This Mac'),
        hasSection: true,
        hasShortcut: true,
        shortcut: '⌘ ,',
        hasDropMenu: true,
      }, {
        name: 'Empty Trash',
        handleButtonFunction: () => console.log('About This Mac'),
        hasSection: true,
        hasShortcut: true,
        shortcut: '⌘ backspace',
      }, {
        name: 'Services',
        handleButtonFunction: () => console.log('About This Mac'),
        hasSection: true,
      }, {
        name: 'Hide Finder',
        handleButtonFunction: () => console.log('About This Mac'),
        hasSection: true,
      },
      {
        name: 'Hide Others',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '⌘ H',
      },
      {
        name: 'Show All',
        handleButtonFunction: () => console.log('About This Mac'),
        enabled: false
      },
    ],
  },
  {
    name: 'File',
    items: [
      {
        name: 'New Finder Window',
        handleButtonFunction: () => console.log('About This Mac'),
        enabled: true,
        hasShortcut: true,
        shortcut: '⌘ N',
      },
      {
        name: 'New Folder with Selection',
        handleButtonFunction: () => console.log('About This Mac'),
        hasShortcut: true,
        enabled: false,
        shortcut: '⇧ ⌘ N',
      },
      {
        name: 'New Smart Folder',
        handleButtonFunction: () => console.log('About This Mac'),
        hasSection: true,
      },
      {
        name: 'New Tab',
        handleButtonFunction: () => console.log('About This Mac'),
        hasShortcut: true,
        shortcut: '⌘ T',
      },
      {
        name: 'Open',
        handleButtonFunction: () => console.log('About This Mac'),
        enabled: false,
        shortcut: '⌘ O',
      },
      {
        name: 'Open With',
        handleButtonFunction: () => console.log('About This Mac'),
        enabled: false,
        hasDropMenu: true,
      },
      {
        name: 'Close Window',
        handleButtonFunction: () => console.log('About This Mac'),
        enabled: false,
        shortcut: '⌘ W',
        hasSection: true,
      },

      {
        name: 'Get Info',
        handleButtonFunction: () => console.log('About This Mac'),
        hasShortcut: true,
        shortcut: '⌘ I',
      },
      {
        name: 'Rename',
        handleButtonFunction: () => console.log('About This Mac'),
        enabled: false,
      },
      {
        name: 'Compress',
        handleButtonFunction: () => console.log('About This Mac'),
        enabled: false,
      },
      {
        name: 'Duplicate',
        handleButtonFunction: () => console.log('About This Mac'),
        hasShortcut: true,
        enabled: false,
        shortcut: '⌘ D',
      },
      {
        name: 'Make Alias',
        handleButtonFunction: () => console.log('About This Mac'),
        hasShortcut: true,
        enabled: false,
        shortcut: '^ ⌘ A',
      },
      {
        name: 'Quick Lock',
        handleButtonFunction: () => console.log('About This Mac'),
        hasShortcut: true,
        enabled: false,
        shortcut: '⌘ Y',
      },
      {
        name: 'Print',
        handleButtonFunction: () => console.log('About This Mac'),
        hasShortcut: true,
        shortcut: '⌘ P',
        enabled: false,
        hasSection: true,
      },
      {
        name: 'Share...',
        enabled: false,
        handleButtonFunction: () => console.log('About This Mac'),
        hasSection: true,
      },
      {
        name: 'Show Original',
        handleButtonFunction: () => console.log('About This Mac'),
        hasShortcut: true,
        enabled: false,
        shortcut: '⌘ R',
      },
      {
        name: 'Add to Sidebar',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '^ ⌘ T',
        enabled: false,
        hasShortcut: true,
      },
      {
        name: 'Move to Trash',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '⌘ Backspace',
        enabled: false,
        hasShortcut: true,
      },
      {
        name: 'Eject',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '⌘ E',
        enabled: false,
        hasShortcut: true,
        hasSection: true,
      },
      {
        name: 'Tags...',
        enabled: false,
        handleButtonFunction: () => console.log('About This Mac'),
        hasSection: true,
      },
      {
        name: 'Find',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '⌘ F',
        hasShortcut: true,
      },
    ],
  },
  {
    name: 'Edit',
    items: [
      {
        name: 'Undo',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '⌘ Z',
        enabled: false,
        hasShortcut: true,
      },
      {
        name: 'Redo',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '^ ⌘ Z',
        enabled: false,
        hasShortcut: true,
        hasSection: true,
      },
      {
        name: 'Cut',
        handleButtonFunction: () => console.log('About This Mac'),
        enabled: false,
        shortcut: '⌘ X',
        hasShortcut: true,
      },
      {
        name: 'Copy',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '⌘ C',
        enabled: false,
        hasShortcut: true,
      },
      {
        name: 'Paste',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '⌘ V',
        enabled: false,
        hasShortcut: true,
      },
      {
        name: 'Select All',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '⌘ A',
        enabled: false,
        hasShortcut: true,
        hasSection: true,
      },
      {
        name: 'Show Clipboard',
        handleButtonFunction: () => console.log('About This Mac'),
        hasSection: true,
      },
      {
        name: 'AutoFill',
        handleButtonFunction: () => console.log('About This Mac'),
        hasDropMenu: true,
      },
      {
        name: 'Start Dictation',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: 'Mic Icon',
        hasShortcut: true,
      },
      {
        name: 'Emoji & Symbols',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: 'Global Icon E',
        hasShortcut: true,
      },
    ],
  },
  // {
  //   name: 'View',
  //   items: [
  //     'as Icons',
  //     'as List',
  //     'as Columns',
  //     'Use Stacks',
  //     'Sort By',
  //     'as Gallery',
  //     'Clean Up',
  //     'Clean Up By',
  //     'Hide Sidebar',
  //     'Hide Preview',
  //     'Hide Toolbar',
  //     'Show All Tabs',
  //     'Hite Tab Bar',
  //     'Hide Path Bar',
  //     'Hide Status Bar',
  //     'Customize Toolbar...',
  //     'Show View Options',
  //     'Show Path Bar',
  //     'Enter Full Screen',
  //   ],
  // },
  // {
  //   name: 'Go',
  //   items: [
  //     'Back',
  //     'Forward',
  //     'Enclosing Folder',
  //     'Recents',
  //     'Documents',
  //     'Desktop',
  //     'Downloads',
  //     'Home',
  //     'Computer',
  //     'AirDrop',
  //     'Network',
  //     'iCloud Drive',
  //     'Shared',
  //     'Applications',
  //     'Utilities',
  //     'Recents Folders',
  //     'Go to Folder...',
  //     'Connect to Server...',
  //   ],
  // },
  // {
  //   name: 'Window',
  //   items: [
  //     'Minimize',
  //     'Zoom',
  //     'Cycle Through Windows',
  //     'Bring All to Front',
  //     'All',
  //     'None',
  //     'Minimize All',
  //     'Arrange in Front',
  //     'Move Tab to New Window',
  //     'Merge All Windows',
  //   ],
  // },
  {
    name: 'Help', items: [
      {
        name: 'Tips for Your Mac',
        handleButtonFunction: () => console.log('About This Mac'),
      },
      {
        name: 'macOS Help',
        handleButtonFunction: () => console.log('About This Mac'),
        shortcut: '⌘ ?',
        hasShortcut: true,
      }
    ]
  },
]
